server:
  port: 8012
spring:
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeout?useUnicode=true&charactor=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: root


# mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-aliases-package: com.tool.entity